##### AutoUpdatePlugins — Velocity (TOML) configuration #####

[updates]
# Minutes between periodic plugin update runs.
interval = 120
# Seconds to wait after proxy startup before the first run.
bootTime = 50
# Optional: GitHub token for Actions/artifact access and higher rate limits.
# Scope: public_repo is sufficient for public repositories.
key = ""

[http]
# Optional explicit User-Agent. If empty, a realistic pool is rotated.
userAgent = ""
# Extra request headers added to every HTTP request.
# Example: [[http.headers]] name = "Header-Name"; value = "Header-Value"
headers = []
# Pool of user agents; the downloader rotates these on retries.
userAgents = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
  "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0",
]

[proxy]
# DIRECT | HTTP | SOCKS
type = "DIRECT"
host = "127.0.0.1"
port = 7890

[behavior]
# Verify downloaded archives/jars by opening them (recommended)
zipFileCheck = true
# Skip replacing if new jar has identical MD5 as the existing one
ignoreDuplicates = true
# Allow GitHub pre-releases globally for release queries
allowPreRelease = false

[behavior.autoCompile]
# Build from source when needed for GitHub repos
enable = true
# Build when a release has no ".jar" assets (zip-only)
whenNoJarAsset = true
# Build from source if default branch is newer than the latest (pre)release by N months
branchNewerMonths = 4

[paths]
# Optional custom directories (empty = defaults)
tempPath = ""
updatePath = ""
filePath = ""

[performance]
# Max parallel downloads (1..CPU cores recommended)
maxParallel = 4
# HTTP connect/read timeouts in milliseconds per request
connectTimeoutMs = 10000
readTimeoutMs = 30000
# Optional per-download hard timeout in seconds; 0 disables
perDownloadTimeoutSec = 0
# Retry behavior for transient HTTP errors (403/429/5xx)
maxRetries = 4
# Exponential backoff base and max in milliseconds
backoffBaseMs = 500
backoffMaxMs = 5000

##### Plugins List (shared with all platforms)
# Edit list.yml created in this directory in the format:
#   {fileSaveName}: {link.to.plugin}
#
# Supported sources: GitHub (Releases & Actions), Jenkins, SpigotMC (Spiget), dev.bukkit, Modrinth, Hangar,
# BusyBiscuit, blob.build, Guizhanss v2, MineBBS, CurseForge, plus generic pages with direct .jar links.
#
# Asset selection:
# - Append [N] to pick the Nth artifact (GitHub/Jenkins)
# - Append ?get=<regex> to match filenames
# - Append ?prerelease=true to allow GitHub pre-releases per-link
# - Append ?autobuild=true to force a source build from a GitHub repo link
