name: AutoUpdatePlugins
version: '5.5'
main: spigot.SpigotUpdate
authors:
  - NewAmazingPVP
description: Automatically updates any spigot plugin
commands:
  update:
    description: Update all plugins in list.yml!
    usage: /update
    permission: autoupdateplugins.update
    default: op