name: AutoUpdatePlugins
version: '11.5'
main: spigot.SpigotUpdate
# hackfix (definitely will not work as intended)
folia-supported: true
authors:
  - NewAmazingPVP
description: Automatically updates any spigot plugin
commands:
  update:
    description: Update all plugins in list.yml!
    usage: /update
    permission: autoupdateplugins.update
    default: op
  aup:
    description: Manage AutoUpdatePlugins
    usage: /aup <subcommand>
    permission: autoupdateplugins.manage
    aliases: [autoupdateplugins]
    default: op
permissions:
  autoupdateplugins.update:
    description: Allows updating plugins
    default: op
  autoupdateplugins.manage:
    description: Allows managing plugin list
    default: op