name: AutoUpdatePlugins
version: '11.0'
main: spigot.SpigotUpdate
# hackfix (definitely will not work as intended)
folia-supported: true
authors:
  - NewAmazingPVP
description: Automatically updates any spigot plugin
commands:
  update:
    description: Update all plugins in list.yml!
    usage: /update
    permission: autoupdateplugins.update
    default: op