# Plugin Updates Configuration
updates:
  # Time between period plugins updates in minutes
  interval: 120

  # Delay in seconds after server startup before updating plugins
  # Change this if plugins are causing errors by installing before they load
  bootTime: 50

# Plugins List Configuration
# Go to the list.yml file created in this same directory and put the plugin information that you want to periodically update in this format:
# {fileSaveName}: {link.to.plugin}
#
# Example list.yml template here: https://github.com/NewAmazingPVP/AutoUpdatePlugins/blob/main/list.yml
# Examples:
#   ViaVersion: "https://www.spigotmc.org/resources/viaversion.19254/"
#   Geyser: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
#   EssentialsXChat: "https://github.com/EssentialsX/Essentials + multi[3]" # For multi-artifact plugins, specify the artifact number within brackets.
#
# The plugin takes in a Spigot/Jenkins/Bukkit/Github/Modrinth/Hangar resource link or a direct link that automatically redirects and downloads the latest release.
# Make sure if it's a Spigot resource link that the resource can be directly downloaded on Spigot itself and not on an external website
# For Bukkit, Jenkins, Github, Modrinth, Hangar links, make sure they just point to the project (not the releases just the main project website)
# For example:
#   - The first example downloads the plugin from https://www.spigotmc.org/resources/viaversion.19254/ and names it ViaVersion (the .jar extension will be added automatically when downloaded)
#   - The second example downloads the Geyser Spigot version and saves it as Geyser
#   - The third example downloads the EssentialsXChat artifact from the EssentialsX project on GitHub. It specifies the artifact number (jar in release bundle) as 3 using the format `multi[3]` at end.
